### ISSUE TITLE
Support for multiple colors

### ISSUE THREAD

**Issue by LordMathis** [LordMathis/hugo-theme-nightfall#30]
Currently the theme uses blue as the primary color for post title and links. The idea is to support different colors via a config option. 

```toml
[params]
colour = "orange"
```

There's a PR #29 with more details which sparked this issue.
