### ISSUE TITLE
Not working disabled metadata

### ISSUE THREAD

**Issue by renanbastos93** [lordmathis/hugo-theme-nightfall#40]
I have setted `showMetadata = false` in config.toml but it doesn't work.

example
```toml
[params]
user = ""
hostname = "renanbastos.dev"
sitedescription = 'Renan Bastos has been working as a Software Engineer for over 9 years with cutting-edge technologies'
showMetadata = false
```

<img width="784" alt="image" src="https://github.com/LordMathis/hugo-theme-nightfall/assets/8202898/45798f23-baad-41a5-b190-2800b8f4ea1b">
